name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - x86_64-linux
          - aarch64-linux
          - x86_64-macos

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@abea47f85e598557f500fa1fd2ab7464fcb39406 # v2.2.1
        with:
          version: 0.12.0

      - name: Build
        run: zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseFast

      - name: Archive
        run: |
          mkdir dist
          cp zig-out/bin/* dist/
          tar -czf app-${{ matrix.target }}.tar.gz -C dist .

      - name: Upload Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          files: app-*.tar.gz
